apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 5Gi  # Adjust the storage capacity as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "D:/Coding/Distributed System Design/Project DSD/Producer/Ingestdata"  # Replace with the actual path on your host machine
