apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-files-pvs
spec:
  capacity:
    storage: 3Gi  # Adjust the storage size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/c/documents/test"  # Adjust the path on Minikube host

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-files-pvcs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi  # Match the storage size from the PersistentVolume