apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    component: zookeeper-app
  type: LoadBalancer
  ports:
  - protocol: 'TCP'
    port: 2181
    targetPort: 2181
  # - protocol: 'TCP'
  #   port: 2000
  #   targetPort: 2000
